/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrame.java
 *
 * Created on 17/03/2010, 20:43:17
 */

package rca.dept.gui.swing;

import java.awt.Color;
import java.awt.Dimension;
import org.jvnet.substance.SubstanceLookAndFeel;
import org.jvnet.substance.skin.BusinessSkin;
import rca.dept.swing.utils.SwingPTBR;

/**
 *
 * @author rennan
 */
public class MainFrame extends javax.swing.JFrame {

    private static MainFrame instance;

    private JPanelLogin jPanelLogin;
    private JPanelFormulario jPanelFormulario;

    public static MainFrame getInstance(){
        if(instance == null)
             instance = new MainFrame();
        return instance;
    }

    /** Creates new form MainFrame */
    private MainFrame() {
        jPanelLogin = new JPanelLogin();
        jPanelFormulario = new JPanelFormulario();
        initComponents();
        setPrivilegy(JPanelLogin.Privilegy.DESCONHECIDO);
        setMinimumSize(new Dimension(700, 450));
        setPreferredSize(new Dimension(700, 450));
        pack();
        transferFocus();
        logout.setText("<html><u>Sair</u></color></html>");
        logout.setForeground(new Color(0, 100, 200));
    }

    public void setPrivilegy(JPanelLogin.Privilegy privilegy) {
        if (privilegy == privilegy.COORDENADOR) {
            jTabbedPane1.add("Novo cadastro", jPanelFormulario);
            jPanelFormulario.setVisible(true);
        }
        else if(privilegy == privilegy.FUNCIONARIO) {
            jTabbedPane1.add("Novo cadastro", jPanelFormulario);
            jPanelFormulario.setVisible(true);
        }
        else if(privilegy == privilegy.DESCONHECIDO){
            jLabel1.setVisible(false);
            logout.setVisible(false);
            jTabbedPane1.remove(jPanelFormulario);
            jTabbedPane1.add("Autenticação", jPanelLogin);
            return;
        }
        jTabbedPane1.remove(jPanelLogin);
        jLabel1.setVisible(true);
        logout.setVisible(true);
        jLabel1.setText("Bem vindo, "+jPanelLogin.getUserName());
        jPanelFormulario.setPrivilegy(privilegy);
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Departamento de Música");

        jLabel1.setText(" ");

        logout.setText("<html><color=#0000FF><u>Sair</u></color></html>");
        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 508, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(logout, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 51, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                .add(jLabel1)
                .add(logout, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(jSeparator1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, 0)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(10, 10, 10)
                .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                .add(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        jPanelLogin.logout();
    }//GEN-LAST:event_logoutMouseClicked



    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SwingPTBR.translate();
//                SubstanceLookAndFeel.setSkin(new BusinessSkin());
                MainFrame.getInstance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel logout;
    // End of variables declaration//GEN-END:variables

}
